### ISSUE TITLE
数据库集合futureaccount中的字段isactive值会变为异常的空字符串“”

### ISSUE THREAD

**Issue by yuwangying** [345161974/CppCTP#14]
{
    "_id" : ObjectId("57c531126efa6339067f3762"),
    "brokerid" : "9999",
    "traderid" : "1601",
    "password" : "123456",
    "userid" : "063802",
    "frontaddress" : "tcp://180.168.146.187:10000",
    "isactive" : "",
    "on_off" : 1,
    "order_ref_base" : "100000001701"
}
![collection-futureaccount](https://cloud.githubusercontent.com/assets/20507267/22151285/7c7c8534-df58-11e6-8997-7e715ca23e3f.png)

**Comment by 345161974** [comment]
原因：客户端与服务端交互，客户端发送期货账户开关协议时服务端对isactive进行了空值更新。

已经修复。
