### ISSUE TITLE
数据库集合futureaccount中的字段order_ref_base存在非12位长度

### ISSUE THREAD

**Issue by yuwangying** [345161974/CppCTP#15]
{
    "_id" : ObjectId("57a346f64c80372f7ea3caed"),
    "brokerid" : "9999",
    "traderid" : "1601",
    "password" : "669822",
    "userid" : "058176",
    "frontaddress" : "tcp://180.168.146.187:10000",
    "isactive" : "1",
    "on_off" : 1,
    "order_ref_base" : "1000000001"
}
![collection-futureaccount](https://cloud.githubusercontent.com/assets/20507267/22151385/c3c834b0-df58-11e6-90f3-44d3706066cf.png)

**Comment by 345161974** [comment]
"order_ref_base" : "1000000001"，这个是初始化值。
实际的报单引用 = 初始化值(自增长) + 策略id(2位)
