### ISSUE TITLE
数据库键名命名不规范、键值类型不统一，不算bug，但是会增加开发出错概率

### ISSUE THREAD

**Issue by yuwangying** [345161974/CppCTP#16]
collection-strategy中存在键名“is_active”，值类型为bool；
collection-futureaccount中存在键名“isactive”，值类型为string
![collection-strategy](https://cloud.githubusercontent.com/assets/20507267/22151488/283bf864-df59-11e6-9705-9e2dbb907ae9.png)
![collection-futureaccount](https://cloud.githubusercontent.com/assets/20507267/22151489/2864ab74-df59-11e6-9b04-7c955d90eac3.png)

**Comment by 345161974** [comment]
暂时不做处理，先关掉。
