### ISSUE TITLE
tick 已上锁，死锁。

### ISSUE THREAD

**Issue by yuwangying** [345161974/CppCTP#28]
tick 已上锁，死锁。
![Uploading QQ图片20170409194151.png…]()

**Comment by yuwangying** [comment]
![qq 20170409194151](https://cloud.githubusercontent.com/assets/20507267/24837072/8ff743da-1d5e-11e7-969f-0fef3fc2fb9a.png)

**Comment by 345161974** [comment]
tick死锁是由于平仓仓位不足导致。
* 测试数据不应该绕过TS端进行平仓
* 遇到tick上锁，需要手动在小蜜蜂端进行仓位调整。
