### ISSUE TITLE
小蜜蜂设置持仓TS端的操作要领

### ISSUE THREAD

**Issue by yuwangying** [345161974/CppCTP#51]
小蜜蜂设置持仓，TS端的操作流程
1）TS通过虚拟平仓的方式更新内存中的持仓明细。如果所有持仓设置为0，则直接清空持仓明细，简单粗暴安全。
2）根据最新的持仓明细计算出持仓变量，这样TS端的持仓明细和持仓变量绝对一致。
3）更新一遍标志位的值：tick锁、任务锁，根据实际情况决定标志位的值，例如设置的持仓是撇退的，任务锁可能就是True。
4）持仓明细和策略参数存入数据库，细节不详述了。

**Comment by yuwangying** [comment]
3）更新一遍标志位的值：tick锁、任务锁
特别是针对策略持仓设置为0之后，tick锁和任务锁一定是恢复到初始值。

**Comment by 345161974** [comment]
经一段时间测试，仓位问题不存在。
