### ISSUE TITLE
小蜜蜂显示满足交易条件，实际无委托

### ISSUE THREAD

**Issue by yuwangying** [345161974/CppCTP#60]
小蜜蜂显示满足交易条件，实际无委托，所有策略都有此情况。
![qq 20170517214805](https://cloud.githubusercontent.com/assets/20507267/26156998/8f658b34-3b4a-11e7-932a-0708f8b61716.png)
![qq 20170517214948](https://cloud.githubusercontent.com/assets/20507267/26157051/be1fcc00-3b4a-11e7-899e-43316b07adb6.png)

**Comment by 345161974** [comment]
#65 bug导致行情驱动阻塞，无法进行发单。

**Comment by 345161974** [comment]
有可能是行情断线导致，该bug转移到 #3 进行跟踪，关闭该bug。
